name: Auto 1 PR Every 2 Hours

on:
  schedule:
    - cron: '0 0 * * *'
    - cron: '0 2 * * *'
    - cron: '0 4 * * *'
    - cron: '0 6 * * *'
    - cron: '0 8 * * *'
    - cron: '0 10 * * *'
    - cron: '0 12 * * *'
    - cron: '0 14 * * *'
    - cron: '0 16 * * *'
    - cron: '0 18 * * *'
    - cron: '0 20 * * *'
    - cron: '0 22 * * *'
  workflow_dispatch:

jobs:
  generate_and_merge_prs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "AutoBot"
          git config --global user.email "autobot@example.com"

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install gh -y

      - name: Authenticate GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "$GH_TOKEN" | gh auth login --with-token

      - name: Generate and Merge 1 PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          i=$((RANDOM % 10000))
          BRANCH="auto-pr-$i-$(date +%s)"
          git checkout main
          git pull origin main
          git checkout -b "$BRANCH"
          echo "Auto change $i at $(date)" > "file-$i.txt"
          git add "file-$i.txt"
          git commit -m "Auto PR $i"
          git push origin "$BRANCH"
          gh pr create --base main --head "$BRANCH" --title "Auto PR $i" --body "Created automatically"
          gh pr merge "$BRANCH" --squash --delete-branch
